## Numpy
- NumPy is a genral purpose array-processing package.
- NumPy was created to work with multidaimensional array.
- It is fundamental package for scintific computing computer.
- It is open source library.

# Why use NumPy ?
- In python we have list that serv the purpose of array, but they are slow to proceiss.
- NumPy  aims to provide an array object that is up to 50X  faster than traditional Python list.
- The array object in NumPy is called ndarray, it is provoding a lots of supporting function that make working with ndarray very easy.
- Arrays are very frequently used in data science , where speed and resource are very important.

In [5]:
# imorting necessary library

!pip install numpy

import numpy as np

In [8]:
#Array creation
a = np.array(10)
type(a)

numpy.ndarray

In [14]:
#zero daimainsional array

In [10]:
z = np.array(10)

In [12]:
z.ndim

0

In [15]:
#one daimainsional array

In [16]:
o = np.array([10,20,30,40])

In [17]:
o.ndim

1

In [18]:
#two daimainsional array 

In [19]:
t = np.array([[60,70,80,90]])

In [20]:
t.ndim

2

In [21]:
# Three daimainsional array

In [22]:
th = np.array([[[11,22,44,33,55]]])

In [23]:
th.ndim

3

In [24]:
# Change the datd type of array element

In [25]:
b = np.array([10,20,30,40])

In [27]:
b.dtype

dtype('int32')

In [28]:
b = np.array([10,20,30,40], dtype = float)

In [29]:
b.dtype

dtype('float64')

In [30]:
b

array([10., 20., 30., 40.])

In [32]:
#for multiple output write Print for each statment

In [34]:
b = np.array([10,20,30,40], dtype = float)
print(b.dtype)
b

float64


array([10., 20., 30., 40.])

# Others way of creating array 
1. arange
2. linspace
3. zeros
4. ones
5. randoms

In [36]:
a = np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
b = np.linspace(1,5,15,)
b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [37]:
b = np.linspace(1,5,15, retstep= True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [41]:
z = np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [43]:
o = np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

r = np.random.rand(5,5)
r

In [46]:
r = np.random.randint(5, size = 10)
r

array([0, 0, 4, 4, 0, 0, 4, 0, 4, 1])

# Slicing and indexing of Arrays 

In [48]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a[0,0]

1

In [50]:
a[1,2]

6

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a[0,1:]

array([2, 3])

In [53]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [59]:
#3 and 4 
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays 

In [61]:
a = np.random.rand(5,2)
a

array([[0.90059562, 0.22208809],
       [0.7264553 , 0.48123431],
       [0.48371738, 0.42877863],
       [0.44089434, 0.992686  ],
       [0.65542894, 0.59222541]])

In [62]:
a.reshape(2,5)

array([[0.90059562, 0.22208809, 0.7264553 , 0.48123431, 0.48371738],
       [0.42877863, 0.44089434, 0.992686  , 0.65542894, 0.59222541]])

In [63]:
a.reshape(10,1)

array([[0.90059562],
       [0.22208809],
       [0.7264553 ],
       [0.48123431],
       [0.48371738],
       [0.42877863],
       [0.44089434],
       [0.992686  ],
       [0.65542894],
       [0.59222541]])

In [64]:
a.reshape(1,10)

array([[0.90059562, 0.22208809, 0.7264553 , 0.48123431, 0.48371738,
        0.42877863, 0.44089434, 0.992686  , 0.65542894, 0.59222541]])

In [65]:
a.reshape(5,-1)

array([[0.90059562, 0.22208809],
       [0.7264553 , 0.48123431],
       [0.48371738, 0.42877863],
       [0.44089434, 0.992686  ],
       [0.65542894, 0.59222541]])

In [66]:
a.reshape(-1,5)

array([[0.90059562, 0.22208809, 0.7264553 , 0.48123431, 0.48371738],
       [0.42877863, 0.44089434, 0.992686  , 0.65542894, 0.59222541]])

# Aggricate function 
- The Python NumPy aggricate function are sum,min,max,mean,avarage,product,stadard deviation,variance,percentile,corrcoef.

In [67]:
a.min()

0.2220880926576918

In [69]:
a.std()

0.2209487436418443

In [70]:
a.var()

0.048818347316909434

# Stacking 
- stacking is used to join two arrays.
- Vartival Stacking
- Horizontal stacking

In [72]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [73]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])